/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthProjectsIndexRouteImport } from './routes/_auth/projects/index'
import { Route as AuthPaintsIndexRouteImport } from './routes/_auth/paints/index'
import { Route as AuthKitsIndexRouteImport } from './routes/_auth/kits/index'
import { Route as AuthProjectsIdRouteImport } from './routes/_auth/projects/$id'
import { Route as AuthPaintsNewRouteImport } from './routes/_auth/paints/new'
import { Route as AuthPaintsPaintIdRouteImport } from './routes/_auth/paints/$paintId'
import { Route as AuthKitsNewRouteImport } from './routes/_auth/kits/new'
import { Route as AuthKitsKitIdRouteImport } from './routes/_auth/kits/$kitId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsIndexRoute = AuthProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPaintsIndexRoute = AuthPaintsIndexRouteImport.update({
  id: '/paints/',
  path: '/paints/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthKitsIndexRoute = AuthKitsIndexRouteImport.update({
  id: '/kits/',
  path: '/kits/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProjectsIdRoute = AuthProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPaintsNewRoute = AuthPaintsNewRouteImport.update({
  id: '/paints/new',
  path: '/paints/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPaintsPaintIdRoute = AuthPaintsPaintIdRouteImport.update({
  id: '/paints/$paintId',
  path: '/paints/$paintId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthKitsNewRoute = AuthKitsNewRouteImport.update({
  id: '/kits/new',
  path: '/kits/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthKitsKitIdRoute = AuthKitsKitIdRouteImport.update({
  id: '/kits/$kitId',
  path: '/kits/$kitId',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthDashboardRoute
  '/kits/$kitId': typeof AuthKitsKitIdRoute
  '/kits/new': typeof AuthKitsNewRoute
  '/paints/$paintId': typeof AuthPaintsPaintIdRoute
  '/paints/new': typeof AuthPaintsNewRoute
  '/projects/$id': typeof AuthProjectsIdRoute
  '/kits/': typeof AuthKitsIndexRoute
  '/paints/': typeof AuthPaintsIndexRoute
  '/projects/': typeof AuthProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthDashboardRoute
  '/kits/$kitId': typeof AuthKitsKitIdRoute
  '/kits/new': typeof AuthKitsNewRoute
  '/paints/$paintId': typeof AuthPaintsPaintIdRoute
  '/paints/new': typeof AuthPaintsNewRoute
  '/projects/$id': typeof AuthProjectsIdRoute
  '/kits': typeof AuthKitsIndexRoute
  '/paints': typeof AuthPaintsIndexRoute
  '/projects': typeof AuthProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/kits/$kitId': typeof AuthKitsKitIdRoute
  '/_auth/kits/new': typeof AuthKitsNewRoute
  '/_auth/paints/$paintId': typeof AuthPaintsPaintIdRoute
  '/_auth/paints/new': typeof AuthPaintsNewRoute
  '/_auth/projects/$id': typeof AuthProjectsIdRoute
  '/_auth/kits/': typeof AuthKitsIndexRoute
  '/_auth/paints/': typeof AuthPaintsIndexRoute
  '/_auth/projects/': typeof AuthProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/kits/$kitId'
    | '/kits/new'
    | '/paints/$paintId'
    | '/paints/new'
    | '/projects/$id'
    | '/kits/'
    | '/paints/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/kits/$kitId'
    | '/kits/new'
    | '/paints/$paintId'
    | '/paints/new'
    | '/projects/$id'
    | '/kits'
    | '/paints'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/dashboard'
    | '/_auth/kits/$kitId'
    | '/_auth/kits/new'
    | '/_auth/paints/$paintId'
    | '/_auth/paints/new'
    | '/_auth/projects/$id'
    | '/_auth/kits/'
    | '/_auth/paints/'
    | '/_auth/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects/': {
      id: '/_auth/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthProjectsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/paints/': {
      id: '/_auth/paints/'
      path: '/paints'
      fullPath: '/paints/'
      preLoaderRoute: typeof AuthPaintsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/kits/': {
      id: '/_auth/kits/'
      path: '/kits'
      fullPath: '/kits/'
      preLoaderRoute: typeof AuthKitsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/projects/$id': {
      id: '/_auth/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthProjectsIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/paints/new': {
      id: '/_auth/paints/new'
      path: '/paints/new'
      fullPath: '/paints/new'
      preLoaderRoute: typeof AuthPaintsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/paints/$paintId': {
      id: '/_auth/paints/$paintId'
      path: '/paints/$paintId'
      fullPath: '/paints/$paintId'
      preLoaderRoute: typeof AuthPaintsPaintIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/kits/new': {
      id: '/_auth/kits/new'
      path: '/kits/new'
      fullPath: '/kits/new'
      preLoaderRoute: typeof AuthKitsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/kits/$kitId': {
      id: '/_auth/kits/$kitId'
      path: '/kits/$kitId'
      fullPath: '/kits/$kitId'
      preLoaderRoute: typeof AuthKitsKitIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthKitsKitIdRoute: typeof AuthKitsKitIdRoute
  AuthKitsNewRoute: typeof AuthKitsNewRoute
  AuthPaintsPaintIdRoute: typeof AuthPaintsPaintIdRoute
  AuthPaintsNewRoute: typeof AuthPaintsNewRoute
  AuthProjectsIdRoute: typeof AuthProjectsIdRoute
  AuthKitsIndexRoute: typeof AuthKitsIndexRoute
  AuthPaintsIndexRoute: typeof AuthPaintsIndexRoute
  AuthProjectsIndexRoute: typeof AuthProjectsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthKitsKitIdRoute: AuthKitsKitIdRoute,
  AuthKitsNewRoute: AuthKitsNewRoute,
  AuthPaintsPaintIdRoute: AuthPaintsPaintIdRoute,
  AuthPaintsNewRoute: AuthPaintsNewRoute,
  AuthProjectsIdRoute: AuthProjectsIdRoute,
  AuthKitsIndexRoute: AuthKitsIndexRoute,
  AuthPaintsIndexRoute: AuthPaintsIndexRoute,
  AuthProjectsIndexRoute: AuthProjectsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
