/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppPaintsIndexRouteImport } from './routes/app/paints/index'
import { Route as AppKitsIndexRouteImport } from './routes/app/kits/index'
import { Route as AppKitsNewRouteImport } from './routes/app/kits/new'
import { Route as AppKitsStockIdRouteImport } from './routes/app/kits/$stockId'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPaintsIndexRoute = AppPaintsIndexRouteImport.update({
  id: '/paints/',
  path: '/paints/',
  getParentRoute: () => AppRoute,
} as any)
const AppKitsIndexRoute = AppKitsIndexRouteImport.update({
  id: '/kits/',
  path: '/kits/',
  getParentRoute: () => AppRoute,
} as any)
const AppKitsNewRoute = AppKitsNewRouteImport.update({
  id: '/kits/new',
  path: '/kits/new',
  getParentRoute: () => AppRoute,
} as any)
const AppKitsStockIdRoute = AppKitsStockIdRouteImport.update({
  id: '/kits/$stockId',
  path: '/kits/$stockId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/kits/$stockId': typeof AppKitsStockIdRoute
  '/app/kits/new': typeof AppKitsNewRoute
  '/app/kits/': typeof AppKitsIndexRoute
  '/app/paints/': typeof AppPaintsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppIndexRoute
  '/app/kits/$stockId': typeof AppKitsStockIdRoute
  '/app/kits/new': typeof AppKitsNewRoute
  '/app/kits': typeof AppKitsIndexRoute
  '/app/paints': typeof AppPaintsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/kits/$stockId': typeof AppKitsStockIdRoute
  '/app/kits/new': typeof AppKitsNewRoute
  '/app/kits/': typeof AppKitsIndexRoute
  '/app/paints/': typeof AppPaintsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/'
    | '/app/kits/$stockId'
    | '/app/kits/new'
    | '/app/kits/'
    | '/app/paints/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/kits/$stockId'
    | '/app/kits/new'
    | '/app/kits'
    | '/app/paints'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/'
    | '/app/kits/$stockId'
    | '/app/kits/new'
    | '/app/kits/'
    | '/app/paints/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/paints/': {
      id: '/app/paints/'
      path: '/paints'
      fullPath: '/app/paints/'
      preLoaderRoute: typeof AppPaintsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kits/': {
      id: '/app/kits/'
      path: '/kits'
      fullPath: '/app/kits/'
      preLoaderRoute: typeof AppKitsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kits/new': {
      id: '/app/kits/new'
      path: '/kits/new'
      fullPath: '/app/kits/new'
      preLoaderRoute: typeof AppKitsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kits/$stockId': {
      id: '/app/kits/$stockId'
      path: '/kits/$stockId'
      fullPath: '/app/kits/$stockId'
      preLoaderRoute: typeof AppKitsStockIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppKitsStockIdRoute: typeof AppKitsStockIdRoute
  AppKitsNewRoute: typeof AppKitsNewRoute
  AppKitsIndexRoute: typeof AppKitsIndexRoute
  AppPaintsIndexRoute: typeof AppPaintsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppKitsStockIdRoute: AppKitsStockIdRoute,
  AppKitsNewRoute: AppKitsNewRoute,
  AppKitsIndexRoute: AppKitsIndexRoute,
  AppPaintsIndexRoute: AppPaintsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
